### PR TITLE
Create Melodramedary

### PR DESCRIPTION
**Pull request by uthuluc**
-spit counter
-suggests spit targets based on eligible quest states
-will helpfully tell you needed itemdrop% thresholds
-creates a Very Important Popup at 100% spit

### CODE REVIEW

**Comment by fredg1** [comment]
upload PRs as drafts, if they were barely started, and not tested :/

**Comment by fredg1** [comment]
could add a reminder for bringing it along when exploring the desert?

**Comment by cdrock** [comment]
@fredg1 Is this still untested?

**Comment by fredg1** [comment]
@cdrock "tested", but never saw it used in-run.
Also, need to test the desert part.

**Pull request merged**
