### PR TITLE
Revamp sausage information.

### PR DESCRIPTION
**Pull request by phulin**
This PR moves all information about sausages into the Resource list instead of the Tasks list. It shows sausage information both in run and in aftercore, and it shows how many you've eaten in addition to how many you have made.

Screenshot:
image

### CODE REVIEW

**Comment by phulin** [comment]
It still uses the existing logic to place it at the top of the screen when the fight is ready. Is there something more than that you want it to do?

**Comment by cdrock** [comment]
Oh interesting. It wasn't showing up for me. Let me run some more tests after RO.

**Comment by phulin** [comment]
It only happens in run right now. We can change that if you want, but I'm not sure my personal preference would pull it to the top for random aftercore play.

**Comment by cdrock** [comment]
Ahh, you're right! Thanks for clarifying.

**Pull request merged**
